name: Cypress Clou

on:
  workflow_dispatch:
    inputs: 
      spec:
        description: Run by cypress command line
        default: cypress/2e2/*
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-lastest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.7
      
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECOR_KEY: 5aa0c744-7de8-4f4c-8db2-e9103d1391cd
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
